name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-go-servers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build app-backend
      run: |
        cd app-backend
        go mod tidy
        go build -v ./...
        go test -v ./...
    
    - name: Build notification-backend
      run: |
        cd notification-backend
        go mod tidy
        go build -v ./...
        go test -v ./...
    
    - name: Run encryption tests
      run: |
        cd notification-backend
        go test -v -run TestEncryption

  build-android:
    steps:
    - uses: actions/checkout@v4

    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.5.0
      with:
        project-path: demo-app
    
    - name: Run Android unit tests
      run: |
        cd demo-app
        ./gradlew test

  go-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: app-backend
    
    - name: Run golangci-lint for notification-backend
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: notification-backend
    
